### ISSUE TITLE
FHEM Python Binding

### ISSUE THREAD

**Issue by royweijers1981** [dominikkarall/fhem_pythonbinding#3]
Hello,

I have a problem. I have set everything but in fhem the python binding and the bindingsio_remote remain disabled. Can you help me with this and or let me know the problem it is in?

greetings Roy

ps: the rights are complete and the owner and group are well in the right place

![image](https://user-images.githubusercontent.com/50567466/97197934-851dc080-17ae-11eb-9b48-9de3ef9cba7b.png)
![image](https://user-images.githubusercontent.com/50567466/97197983-98309080-17ae-11eb-84b4-a6d2b2f9f9de.png)
![image](https://user-images.githubusercontent.com/50567466/97198057-af6f7e00-17ae-11eb-83be-cba5c74a274d.png)

**Comment by dominikkarall** [comment]
Hi,
have you tested starting fhem_pythonbinding from console? What happens if you type
```
sudo systemctl start fhem_pythonbinding
```
Check also the log file
```
journalctl -u fhem_pythonbinding
```

**Comment by royweijers1981** [comment]
> ```
> journalctl -u fhem_pythonbinding
> ```


that works

![image](https://user-images.githubusercontent.com/50567466/97205140-57894500-17b7-11eb-80b4-dd89795865ac.png)

**Comment by royweijers1981** [comment]
> ```
> journalctl -u fhem_pythonbinding
> ```
something goes wrong in the log, how can I solve it

![image](https://user-images.githubusercontent.com/50567466/97205258-830c2f80-17b7-11eb-9c41-74eb4efb87d5.png)

**Comment by dominikkarall** [comment]
Are you running python3.7 or higher?

**Comment by royweijers1981** [comment]
> Gebruik je python3.7 of hoger?

Yes I think so. have also run apt-get update
how can i see that?

**Comment by dominikkarall** [comment]
```
python3 --version
```

**Comment by royweijers1981** [comment]
![image](https://user-images.githubusercontent.com/50567466/97206550-290c6980-17b9-11eb-9881-86e8e4344fdb.png)


> ```
> python3 --version
> ```
![image](https://user-images.githubusercontent.com/50567466/97206569-3164a480-17b9-11eb-832c-07e6056a11e6.png)

**Comment by dominikkarall** [comment]
```
sudo apt install python3.7
```
It might be that you need to update your distribution to buster. I'm not sure if below buster python 3.7 is available.

**Comment by royweijers1981** [comment]
> ```
> sudo apt install python3.7
> ```
> 
> It might be that you need to update your distribution to buster. I'm not sure if below buster python 3.7 is available.


I'm not sure if I installed buster at the time. I do see that he cannot find package 3.7

**Comment by royweijers1981** [comment]
I still have stretch I see :-)

**Comment by dominikkarall** [comment]
Ok, that requires an update to buster ;)

If you have further questions after the installation, don't hesitate to open a new issue.

**Comment by royweijers1981** [comment]
> Ok, dat vereist een update naar buster;)
> 
> Als u na de installatie nog vragen heeft, aarzel dan niet om een ​​nieuw nummer te openen.

thnks for you help!!
