### ISSUE TITLE
miflora - request for additional functionality

### ISSUE THREAD

**Issue by VinceMasuka** [dominikkarall/fhem_pythonbinding#6]
Hidey ho!

Thanks for your fast implementation of the miflora module!

The only thing I'm missing is some way to completely disable the module from actively reading the sensor. See, it's battery driven. Plus you might not need to pull by some interval (most probably your plant feels pretty much the same now than two hours ago), but just by the time you want to know how your plant is doing (perhaps you just re-planted it or you came with some water around the corner). That would save battery power of the sensor, too. On top of this you have your smart home system around to manage that...
Speaking of that:
With the ability to disable the "interval pulling" some function to actively pull the current status might come handy here, too.

So request is:

- ability to disable the module completely from pulling anything (e.g. "attr miAloe disable 1")

- ability to request current status (to update readings at once - e.g. "get miAloe sensorData")

Thanks!

Regards
VinceMasuka

**Comment by dominikkarall** [comment]
Hi,

that's definitely a useful feature. I wouldn't use disable, as that normally disables the module completely in FHEM.

What do you think about:
 - attr miAloe poll_type manual/interval
 - set miAloe update

poll_type = manual would disable the interval. I need to check if I can use `get` to update the readings as I haven't used it till now in fhem_pythonbinding.

**Comment by VinceMasuka** [comment]
Even better! I would really appreciate if you can make that happen...

**Comment by dominikkarall** [comment]
https://github.com/dominikkarall/fhem_pythonbinding/commit/94bf8f8d3c0be0e91bea66bd7815e1686d03b59e

 - Added poll_type attribute
 - Added set ... update

Please let me know if it works. Thx for testing!

**Comment by VinceMasuka** [comment]
I had some issues out of FHEM, telling about state "pythonbinding timeout", but after a minute it now shows constantly up as state "online". This state remains after host restart, too.

It looks like it polls data through the set command, just a few seconds after command was executed (only updates readings that really changed). 

It looks like it doesn't start something automatically after poll_type is set to manual.

I'll put it to the test by feeding the pythonbinding with a lot more sensors, but up until now this looks just sweet! Thanks a lot!

Regards
VinceMasuka

**Comment by dominikkarall** [comment]
Ok, great! It could be that a timeout happend when you restarted fhem_pythonbinding, it shouldn't happen during normal operations.

If any issues happen, please open a new issue. Thx!
